### ISSUE TITLE
Incorrect `print` statement in DCOS CLI

### ISSUE THREAD

**Issue by timfallmk** [mesosphere/dcos-kubectl#4]
Running any DCOS CLI commands involving kubernetes fail:
```shell
root@009aad79cd35:/dcos# dcos
Traceback (most recent call last):
  File "/root/.dcos/subcommands/kubernetes/env/bin/dcos-kubernetes", line 9, in <module>
    load_entry_point('dcos-kubernetes==0.1.0', 'console_scripts', 'dcos-kubernetes')()
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/dcos_kubernetes/cli.py", line 50
    print "Download kubectl from " + url
                                 ^
SyntaxError: Missing parentheses in call to 'print'
Traceback (most recent call last):
  File "/root/.dcos/subcommands/kubernetes/env/bin/dcos-kubectl", line 9, in <module>
    load_entry_point('dcos-kubernetes==0.1.0', 'console_scripts', 'dcos-kubectl')()
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.dcos/subcommands/kubernetes/env/lib/python3.4/site-packages/dcos_kubernetes/cli.py", line 50
    print "Download kubectl from " + url
                                 ^
SyntaxError: Missing parentheses in call to 'print'
Traceback (most recent call last):
  File "/dcos/bin/dcos-help", line 11, in <module>
    sys.exit(main())
  File "/dcos/lib/python3.4/site-packages/dcoscli/help/main.py", line 28, in main
    return _main()
  File "/dcos/lib/python3.4/site-packages/dcoscli/main.py", line 144, in wrapper
    result = func(*args, **kwargs)
  File "/dcos/lib/python3.4/site-packages/dcoscli/help/main.py", line 42, in _main
    return cmds.execute(_cmds(), args)
  File "/dcos/lib/python3.4/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/dcos/lib/python3.4/site-packages/dcoscli/help/main.py", line 91, in _help
    .make_command_summary_string(sorted(results))
  File "/usr/local/lib/python3.4/concurrent/futures/_base.py", line 549, in result_iterator
    yield future.result()
  File "/usr/local/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/local/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/dcos/lib/python3.4/site-packages/dcos/subcommand.py", line 131, in documentation
    return (path_noun, info(executable_path, path_noun))
  File "/dcos/lib/python3.4/site-packages/dcos/subcommand.py", line 146, in info
    [executable_path, path_noun, '--info'])
  File "/usr/local/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/root/.dcos/subcommands/kubernetes/env/bin/dcos-kubernetes', 'kubernetes', '--info']' returned non-zero exit status 1
```

**Comment by sttts** [comment]
Which python version? With 2.7.something on Mac everything is fine.

**Comment by sttts** [comment]
@timfallmk can you check out https://github.com/mesosphere/dcos-kubectl/pull/6 ?
